### PR TITLE
Updates for Rails 4.x.

### PR DESCRIPTION
**Pull request by ernie**
So, I didn't bump a version for this yet, but it's needed for some work you know about, @leshill. Could you eyeball this and let me know if it looks good to you?

### CODE REVIEW

**Comment by leshill** [comment]
@ernie LGTM 👍

**Comment by ernie** [comment]
@leshill I added a few updates, I think these should be OK. Would love to know if you agree. All tests pass. Mostly just want to make sure since there are some non-cz folks who use this.

**Comment by leshill** [comment]
@ernie 👍  The two `if` statements without a default is funny-looking, but guessing that there are only two options.

**Comment by ernie** [comment]
@leshill Squashed.

**Comment by ernie** [comment]
@leshill Re: the two if statements, I agree. This structure was taken directly from [the official recommendations](https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#registering-all-versions-of-sprockets-in-processors).

If this all looks good, can you merge and cut a release? I don't think I have the ability to push this gem to Rubygems.

**Pull request merged**
